### ISSUE TITLE
using restructedtext failed with exception

### ISSUE THREAD

**Issue by solsticedhiver** [hyde/hyde-old#11]
hi.
i simply changed index.html to include some tests. i.e. using snippets on the main page of hyde http://github.com/lakshmivyas/hyde

so trying to use restructedtext i paste

<pre><p> I love templates. </p>
{% restructuredtext %}
Render this **content all in reStructuredText**.

     Writing in reStructuredText is also quicker than
     writing in HTML.

#. Or at least that is my opinion.
#. What about you?

{% endrestructuredtext %}
</pre>

and when i run 

<pre>$ ./hyde.py -g -s /tmp/test/

INFO:Pre processing /tmp/test[2010-01-28 22:03:56,732]
INFO:Processing /index.html[2010-01-28 22:03:56,733]
***********************
Error while rendering page /index.html
***********************
Generation Failed
(<type 'exceptions.AttributeError'>, AttributeError("class _HydeDefaults has no attribute 'RST_SETTINGS_OVERRIDES'",), &lt;traceback object at 0x8e68b6c&gt;)
</pre>

moreover some things have been quickly written. 
because line 73 of ./hydeengine/templatetags/aym.py must be 
print u"Requires docutils library to use reStructuredText tag."

i am using docutils-0.6

if i comment line 76-77 of ./hydeengine/templatetags/aym.py, it seems to work.

**Comment by JoshRosen** [comment]
It looks like the default settings.py file doesn't specify a setting for `RST_SETTINGS_OVERRIDES` and no default setting is specified in `_HydeDefaults`.  Adding 

```
RST_SETTINGS_OVERRIDES = None
```

to your settings.py file should fix this for your site.

**Comment by JoshRosen** [comment]
I've got a commit (5d5e179e02650f37b17015a24aa38f51bfba22ca) that fixes this issue in my repo.

**Comment by solsticedhiver** [comment]
what is supposed to do this variable ?
is it supposed to be used by the user in settings.py ?

**Comment by JoshRosen** [comment]
It's supposed to be used for configuring reStructuredText, by assigning `RST_SETTINGS_OVERRIDES` a dictionary of setting names and values.  For more information about the configuration options, see the [docutils configuration documentation](http://docutils.sourceforge.net/docs/user/config.html).

**Comment by navilan** [comment]
@joshrosen - thanks, merged your changes. Added RST_SETTINGS_OVERRIDES to _HydeDefaults as well.

**Comment by solsticedhiver** [comment]
there is a problem with commit cd3bc0f158d64c039da52eb49ea997bcd78443c0

when i run hyde i got the error:
    Generation Failed
    (<type 'exceptions.TypeError'>, TypeError("**init**() got an unexpected keyword argument 'extension_configs'",), <traceback object at 0x8aa2464>)
because of line 61 in ./hydeengine/templatetags/aym.py

i understood that hyde used markdown2-1.0.1 but extension_configs is only in markdown-2.0.3

so please choose between the 2.

also. i saw some tests in a test dir. what are they for ? if they can't catch up a simple error like that ?

**Comment by navilan** [comment]
@solsticedhiver - Sorry about the markdown error. You are right that this should have been caught in a test or before committing. Will get it fixed.
