### ISSUE TITLE
Hyde does not work with markdown2

### ISSUE THREAD

**Issue by navilan** [hyde/hyde-old#15]
See http://github.com/lakshmivyas/hyde/issues/closed#issue/11/comment/127370 for background.

**Comment by solsticedhiver** [comment]
in ./tests/test_siteinfo.py and in ./hydeengine/templatetags/aym.py, care is taken to test for markdown2 module and then, if it fails, try to import markdown. 

but in ./hydeengine/templatetags/hydetags.py line 293, there is no such test.
one use
    import markdown

**Comment by navilan** [comment]
Thanks I didn't notice that. 

The issue itself is not treating markdown2 and markdown as separate tags. So my fix is to make them explicitly different. If someone wants to use markdown2, they should use the markdown2 tag.  How does that sound?

**Comment by solsticedhiver** [comment]
i don't know; it complicates things
may be you can still test for markdown2 in ./hydeengine/templatetags/hydetags.py like in the other file
    try:
        import markdown2 as markdown
    except ImportError:
        import markdown
    except ImportError:
        print u"Requires Markdown library to use Markdown tag."
        raise

and use extension_configs only if markdown is used and not for markdown2.

**Comment by navilan** [comment]
How does it complicate things? Given that they have taken their own course, if I choose markdown2 over markdown I make a choice and that should be reflected in my template tags. No? Also Explicit > Implicit?

Moreover, markdown2 has its own extras and other parameters. If we choose this road essentially we would be creating conditional branches in the code that are bound to fail when one library gets enhanced.

The place where it does become complicated is IncludeText - which probably needs an overhaul with directives on what filters to run.

**Comment by solsticedhiver** [comment]
ok. as you like. i let the others, if any, tell about what they think.

moreover i don't use currently markdown ;-). it was just a left-over tag that triggered the bug i mentionnned elsewhere

**Comment by navilan** [comment]
Sounds good :) I pushed the changes. We can revisit it if someone brings it up.

**Comment by solsticedhiver** [comment]
ahem
there is a typo that cause an exception when using markdown2
    Generation Failed
    (<type 'exceptions.NameError'>, NameError("global name 'extensions' is not defined",), <traceback object at 0x8bbb0a4>)

the patch:

```
diff --git a/hydeengine/templatetags/aym.py b/hydeengine/templatetags/aym.py
index b18521d..46996b5 100644
--- a/hydeengine/templatetags/aym.py
+++ b/hydeengine/templatetags/aym.py
@@ -32,7 +32,7 @@ class TextileNode(template.Node):
 def markdown2Parser(parser, token):
     nodelist = parser.parse(('endmarkdown2',))
     parser.delete_first_token()
-    return Markdown2Node(nodelist, extensions)
+    return Markdown2Node(nodelist)
```

**Comment by navilan** [comment]
How thorough of me :). Fixed.

**Comment by jacqueminv** [comment]
> choose markdown2 over markdown I make a choice and that should be reflected in my template tags.

I fully agree. Even if markdown and markdown2 are similar there are still different libraries with their own evolutions, splitting their use will keep things lot more simple.
