### ISSUE TITLE
Site Pre/Post Processors on Windows

### ISSUE THREAD

**Issue by tombell** [hyde/hyde-old#24]
The pre and post site processors look like they're not being used on Windows, even when using them in the settings.py

**Comment by tombell** [comment]
I've fixed the problem on my own fork, going to see if any other problems arise, and try fixing them.

**Comment by navilan** [comment]
Will check it out. Unfortunately, I don't have windows readily available (my VM is toast). So it might take a day or two before I get to merge the fork.

Thanks.
