### ISSUE TITLE
Point me in the right direction

### ISSUE THREAD

**Issue by sethlesky** [hyde/hyde-old#25]
This isn't really an issue.

I'm looking to be pointed in the right direction regarding two customizations I'd like to make.
1) How to change the order of navigation items. 
2) How to have the index display the content of a static page, like about.html instead of the latest blog entry.

Regards,
-SL

**Comment by navilan** [comment]
Hi,

For 1) I would either
a. Create a list in the settings file that specifies the order (or)
b. Make the navigation static (in a separate template that can be {% include %}'ed

2) You can use the {%render_excerpt %} tag for that purpose. 

http://groups.google.com/group/hyde-dev would be a better place for such conversations.
