### ISSUE TITLE
HTML tags encoded in page.variable string

### ISSUE THREAD

**Issue by louquillio** [hyde/hyde-old#27]
I abstracted some data points to page variables, so I can easily change the presentation of a large table:  change the text in these vars, style that text, substitute an image for the text, etc.

When a page.var contains only a simple string, all is good, but any HTML I include in the string is entity-encoded before being inserted into the output.  Not what I expected.  I've tried escaping the affected chars, but no luck.

How can I get Hyde to leave the contents of these string variables alone?  Thanks.

LQ

**Comment by navilan** [comment]
Hi,

You can use the `safe` Django filter to make sure it does not get encoded. For example, lets say you are using html code in your title variable, you can use:

`{{page.title|safe}}` to get the content unencoded.

Check these out to learn more:
- Django autoescape tag: http://docs.djangoproject.com/en/dev/ref/templates/builtins/#autoescape
- Django Safe filter:
  http://docs.djangoproject.com/en/dev/ref/templates/builtins/#safe

**Comment by louquillio** [comment]
Sorry, this reply got caught in my spam filter.

Thanks.  Works well.  BTW, I'm using hyde for most of http://www.webmproject.org/.

LQ

**Comment by navilan** [comment]
Nice. Feel free to add it to the wiki (http://wiki.github.com/lakshmivyas/hyde/sites-using-hyde). I will also add it to the Hyde sites page (unless you have objections).

**Comment by louquillio** [comment]
We're FOSS, and we support FOSS.  No objections.

LQ
