### ISSUE TITLE
Non-root site not browseable under hyde.py webserver

### ISSUE THREAD

**Issue by seandavi** [hyde/hyde-old#32]
I have a site that sits at my home directory, not the server root.  This works fine after deployment with the settings:

```
SITE_ROOT = "/~sdavis/"
SITE_WWW_URL = "http://watson.nci.nih.gov/"
```

However, when I use the webserver to preview the site, I end up with the content sitting at the server root but the URLs being generated with the SITE_ROOT included.  It seems to me that the cherrypy webserver should be serving on the complete URL and not at the server root when SITE_ROOT is not "/" but is something else.  Perhaps I have missed something, though.

I am using hyde version 0.4.

**Comment by JoshRosen** [comment]
I just committed a fix to my fork:

http://github.com/JoshRosen/hyde/commit/bfc080ae26fab99923586eef24c9143408ad082a

**Comment by seandavi** [comment]
I tested your fork, Josh, and it fixes the problem I described.  Thanks.
