### ISSUE TITLE
YAML tags fail when their text contains a colon

### ISSUE THREAD

**Issue by chetan51** [hyde/hyde-old#35]
If I have this at the top of one of my pages:

```
{%hyde
     title: Python: An Interactive Tutorial
%}
```

It will fail because of the colon after "Python". How am I supposed to generate that particular title?

**Comment by JoshRosen** [comment]
Enclosing the title in quotation marks will properly [escape the colon](http://perfectionlabstips.wordpress.com/2008/10/29/how-to-escape-colon-character-in-yaml/); try    

```
{%hyde
     title: "Python: An Interactive Tutorial"
%}
```

**Comment by chetan51** [comment]
Oh shit, thanks! Can I suggest that the README for Hyde be changed to make all the YAML `title`s enclosed in double quotation marks? This is a good practice and should reduce confusion with special characters like the colon.
