### ISSUE TITLE
directory constants should be independent of settings.py location

### ISSUE THREAD

**Issue by patrickboe** [hyde/hyde-old#37]
When you specify LAYOUT_DIR, CONTENT_DIR, and MEDIA_DIR values that are not in the same directory with settings.py, you get errors during generate. For instance, I want the root directory of my project to contain two directories: src and deploy, deploy being a git ignored throwaway directory, src containing everything I need to generate deploy. To accomplish this, I first tried to put a settings.py at the root of my project with directory settings like this:

ROOT_PATH = os.path.abspath(os.path.dirname(**file**))
SRC_DIR = os.path.join(ROOT_PATH,'src')
LAYOUT_DIR = os.path.join(SRC_DIR, 'layout')
CONTENT_DIR = os.path.join(SRC_DIR, 'content')
MEDIA_DIR = os.path.join(SRC_DIR, 'media')
DEPLOY_DIR = os.path.join(ROOT_PATH, 'deploy')
TMP_DIR = os.path.join(ROOT_PATH, 'deploy_tmp')

This yielded an error on line 58 of processor.py, in extract_processors: 
AttributeError: 'SiteNode' object has no attribute 'fragment'

Next, I put settings.py at the root of my src directory, and was able to generate deploy as a sibling of src like this:

ROOT_PATH = os.path.abspath(os.path.dirname(**file**))
PROJ_PATH, whatevs = os.path.split(ROOT_PATH)
LAYOUT_DIR = os.path.join(ROOT_PATH, 'layout')
CONTENT_DIR = os.path.join(ROOT_PATH, 'content')
MEDIA_DIR = os.path.join(ROOT_PATH, 'media')
DEPLOY_DIR = os.path.join(PROJ_PATH, 'deploy')
TMP_DIR = os.path.join(PROJ_PATH, 'deploy_tmp')

but I wasn't super happy with settings.py being there, so i tried creating a src/build directory and putting settings.py in there, using these settings:

ROOT_PATH, foo = os.path.split(os.path.abspath(os.path.dirname(**file**)))
PROJ_PATH, bar = os.path.split(ROOT_PATH)
LAYOUT_DIR = os.path.join(ROOT_PATH, 'layout')
CONTENT_DIR = os.path.join(ROOT_PATH, 'content')
MEDIA_DIR = os.path.join(ROOT_PATH, 'media')
DEPLOY_DIR = os.path.join(PROJ_PATH, 'deploy')
TMP_DIR = os.path.join(PROJ_PATH, 'deploy_tmp')

This yields a recursion overflow during some kind of directory traversal in siteinfo.py, line 521.

I admit I could just be doing it wrong - but my experiences here seem to indicate that there is some dependency on python.py being in the same directory with the layout, media, and deploy directories, which I wouldn't think there should be. It prevents, for instance, projects that use a standard Maven directory structure. 

One extra bit of information, in case it's useful: in each of the failures mentioned above, the deploy and deploy_temp directories got created successfully in the desired place before the script crashed.

Thanks so much for such an awesome project! I'm happy to have found it.

**Comment by navilan** [comment]
Hi Patrick,

Hyde had indeed made an assumption about the directory structure - causing the problems you highlighted above. 

I have added support for an extra attribute, SRC_DIR, in settings.py. SRC_DIR, if defined, is used as the root directory of the site instead of the default site_path.

Let me know if you still have issues.

Thanks
Lakshmi.

**Comment by patrickboe** [comment]
Worked like a charm. Thanks so much for your help.
