### ISSUE TITLE
Strange issue with markdown and BracketNode's usage of HTML comments

### ISSUE THREAD

**Issue by hugovincent** [hyde/hyde-old#41]
I'm having a strange problem with recent versions of Markdown (2.0.3 or git-head) giving up on processing posts/articles when they contain HTML comments produced by BracketNode ( `<!-- Hyde::Excerpt::Begin -->` for example). What happens is that some or all of the markdown syntax to be processed isn't processed. This happens even when markdown is run externally from Hyde, with the command line `markdown_py` (sometimes just `markdown`) command. Maybe Hyde could consider some other way of bracketing content for future versions, as it would appear that this HTML comment approach also has issues in other text processors (see other issues).

My super-nasty hackish patch to work around this is here:
https://github.com/hugovincent/hyde/commit/bb9638312712352f9bd47e3603e2cf186658264e

It would be great if a better solution could be arrived at.

**Comment by hugovincent** [comment]
Forgot to add than my platform is OS X 10.6.5 and markdown 2.0.3 was installed with easy_install and the git checkout using the standard setup.py (both installed and tested separately then cleanly uninstalled), and that my markdown extensions are: `MD_EXTENSIONS = ['footnotes', 'abbr', 'toc', 'codehilite', 'tables', 'def_list']` (although the problem remains even when disabling all of the extensions). 

I haven't tested really old versions, but with 2.0.2, 2.0.1, and 2.0, the same problem occurs. I can therefore conclude that while the problem originates in `markdown`, it was exposed either by Hyde updates (tested with 0.5.1) or something unusual in my layout/templates. Having said that, it would appear even running `markdown test/dst_test_markdown.html` shows it not processing markdown correctly (see unprocessed markdown after Excerpt bracketing comment).

**Comment by navilan** [comment]
Hi,

I am planning to rewrite excerpts using the new {%reference%} tag. It will solve these problems.

For now you can use the `reference` tag directly instead of `excerpt`

In the file to be excerpted, use:

```
 {% reference excerpt %}

  Your content

 {% endreference %}
```

Wherever you want to display the excerpt use:

```
 {% refer to "relative path" as var %}

 {{var.excerpt}}
```

Thanks
Lakshmi
