### ISSUE TITLE
"date" filter doesn't support 'B'  - locale's full month name (e.g., January) 

### ISSUE THREAD

**Issue by majek** [hyde/hyde-old#44]
Tag: {{ post.created|date:"B" }}
fails with:
Generation Failed
(<type 'exceptions.NotImplementedError'>, NotImplementedError(), <traceback object at 0x1c30b90>)

**Comment by navilan** [comment]
Hi,

This is as expected:
http://docs.djangoproject.com/en/dev/ref/templates/builtins/?from=olddocs#date

Perhaps 'F' is what you should be using?

**Comment by majek** [comment]
Right, both man date(1) and Jekyll implement 'B' as full month name and 'F' as full date. But fair enough, thanks for the answer!
