### ISSUE TITLE
Bug in new Categories Manager

### ISSUE THREAD

**Issue by eugenkiss** [hyde/hyde-old#45]
There is a bug in the new categories manager. When clicking on a category on an archives page the category urls do not match the category names anymore. 

For example, have a look at this website: http://www.poxd.org/blog/index.html

When hovering over the category links everything seems fine and the names match the links. However, when clicking on 'open source' and inspecting the categories on that page (http://www.poxd.org/archives/open+source.html) almost all categories link to http://www.poxd.org/archives/open+source.html although their correct name is shown.

**Comment by navilan** [comment]
Yeah, weird. I see that lectures.html is okay though. Investigating now.

**Comment by navilan** [comment]
Fixed: https://github.com/lakshmivyas/hyde/commit/59d22eac0fdda76fa2592668154bbcfd90b8623e

**Comment by eugenkiss** [comment]
Thanks! Works as expected now!
