### ISSUE TITLE
Site renders on Windows 7 when I remove the png file form prerendered. Some issue with utf8 ?

### ISSUE THREAD

**Issue by tooh** [hyde/hyde-old#46]
INFO:Processing /prerendered/hyde-icon.png[2010-12-26 17:04:00,822]

---

Error while rendering page /prerendered/hyde-icon.png

---

Generation Failed
(<type 'exceptions.UnicodeDecodeError'>, UnicodeDecodeError('utf8', '\x89PNG\n',
 0, 1, 'invalid start byte'), <traceback object at 0x02103CB0>)

**Comment by navilan** [comment]
Hi, 

I don't have a windows machine at my disposal right now. Will respond as soon as I make one with parallels.

**Comment by navilan** [comment]
The issue is with the path separator:

For now you can make the following change in settings.py under CONTENT_PROCESSORS:

'prerendered/' to 'prerendered\'

This allows generating the site without any issues. I will keep this in mind for the next version. Thanks.

**Comment by mlt** [comment]
This is still relevant. I think it would be nice to add a note to main README so new users like me are not confused when running on win32.
Also cssmin should be added to requirements.txt as I had to install it manually for default template, though not a big deal with pip.
P.S. 'prerendered\' should be 'prerendered\\' of course, i.e. with extra '\'
