### ISSUE TITLE
AttributeError with specific _atom.xml

### ISSUE THREAD

**Issue by tombell** [hyde/hyde-old#47]
I'm using the following code for my _atom.xml (https://gist.github.com/755575), however I get the following error when generating my site.

```
***********************
Error while rendering page /feed/
***********************
Generation Failed
(<type 'exceptions.AttributeError'>, AttributeError("'str' object has no attribute 'walk_pages'",), <traceback object at 0x0217E990>)
```

**Comment by navilan** [comment]
Hi,

The same code works well for me. Can you also gist your settings.py file?

**Comment by tombell** [comment]
https://gist.github.com/757933

I tried running it in Cygwin, and it works fine, I'm guessing it's another problem with Hyde and Windows.

**Comment by navilan** [comment]
yes, I think your preprocessors must be changed to:

SITE_PRE_PROCESSORS = {
    '\' : {
        'hydeengine.site_pre_processors.NodeInjector' : {
            'variable' : 'blog_node',
            'path' : 'content\blog',
        }
    }
}

But cygwin is definitely a better solution :)

**Comment by tombell** [comment]
Changing the / to \ seems to have fixed it. Cheers.
