### ISSUE TITLE
Context variables not inherited?

### ISSUE THREAD

**Issue by nonphotorealist** [hyde/hyde-old#59]
Context variables defined using the {% hyde %} tag are not being inherited by an extending template.  Is that by design, or is it a bug, or am I doing something wrong?

**Comment by navilan** [comment]
Hi,

Its by design (perhaps a lack of feature).  Variables have to be defined in the leaf - page.

There is metadata inheritance in the new version: http://github.com/hyde/hyde. Its still not supported at the template level, but you can do site -> folder - file.

**Comment by nonphotorealist** [comment]
I see. Thank you.

I was trying to use it to supply a default value for a page context variable.   Is there another means of doing that?

**Comment by navilan** [comment]
Unfortunately, not in this version. You can do it in the newer version very easily. 

The best way in 0.5.3 is to use the template default. For example:

```
{{ page.title|default: 'My Website' }}
```
