### ISSUE TITLE
Why is pip needed?

### ISSUE THREAD

**Issue by alanhogan** [hyde/hyde-old#64]
pip seems new and fairly rare, compared to easy_install which I already have installed. I haven’t been able to figure out how to actually install pip.

I know I should just suck it up, and I’m going to plow through this, but I’m not sure it’s quite the friendliest beginning of my relationship with hyde.

**Comment by alanhogan** [comment]
Relatedly — I just tried `easy_install hyde` — is that a workable option?

**Comment by navilan** [comment]
Hi,

Yes, `easy_install` works as well. pip is much more nicer though :)

BTW - `pip install hyde` or `easy_install hyde` will install hyde from http://github.com/hyde/hyde - docs are over here: http://hyde.github.com.
