### ISSUE TITLE
What is the hyde 0.8 equivalent of generate_clean_urls?

### ISSUE THREAD

**Issue by alanhogan** [hyde/hyde-old#65]
The 0.4/0.5-era directions for `GENERATE_CLEAN_URLS` don’t seem to apply to v0.8. What’s to be done?

**Comment by navilan** [comment]
Hi,

The 0.8 equivalent is the url cleaner plugin:
https://github.com/hyde/hyde/blob/master/hyde/ext/plugins/urls.py

Also, please add these issues to the http://github.com/hyde/hyde repository for the benefit of all.

Also note that the wiki on this repository is invalid for http://github.com/hyde/hyde - the best but incomplete documentation for the newer version is http://hyde.github.com
