### ISSUE TITLE
Better support for extensionless URLs

### ISSUE THREAD

**Issue by alanhogan** [hyde/hyde-old#66]
I’m not using .html extensions anywhere. `/about`, not `/about.html`.

Two problems I have run into:
1. Node links seem get .active classes in the `nav` macro, but not pages, including the home page.
2. Links generated from e.g. a blog index end in `.html`, which means an extra redirection (or 404 if I were lazier) in my environment.

It seems to me the core cause is there is no configuration option to this effect.  I guess a big part of it would be having `FS.get_relative_path` omit the file extension when pages are configured to not use the .html extension.

**Comment by navilan** [comment]
Hey,

Assuming that this is on the wrong repository. Please take a look at:
https://github.com/hyde/hyde/blob/master/hyde/ext/plugins/urls.py#L22-33

**Comment by alanhogan** [comment]
Er, yes, wrong repo. Sorry.
