### ISSUE TITLE
refer no longer pulling in content

### ISSUE THREAD

**Issue by davefowler** [hyde/hyde-old#76]
the behavior of refer seems to have changed or been broken in commit 287042b2d5a0686e115103dad548d6aed0f6d7e2. 

Before that commit the results of the following code 

{% refer res.url as post %}
{{ post }}

are:

 {'parent_resource': /var/chartio-hyde/content/blog/index.html, 'content': u'BLOG CONTENT IS SUCCESSFULLY HERE'}

but after that changeset the results are:

 {'parent_resource': /var/chartio-hyde/content/blog/index.html, 'html': , 'resource': None} 

I can now access the "content" in "html" instead, but it seems to also break marks.  I for example want to use

{{ post.article }}

where article should be filled in by the contents of {% mark article %}.  Is this a known intentional change?  How should the new way work?

**Comment by navilan** [comment]
This issue is for the new hyde: https://github.com/hyde/hyde. 

---

Please try:

```
{% refer res.relative_path as post %}
{{ post }}
```

**Comment by davefowler** [comment]
That works great.  Thanks.
