### ISSUE TITLE
Config file inheritance doesn't work as documented

### ISSUE THREAD

**Issue by ghost** [hyde/hyde-old#77]
Could swear I already filed this, but it might have been in some other repo that was linked to by one of the two Hyde sites that haven't been updated in ages. 

Long story short, `extends: site.yaml` doesn't seem to actually do anything.

**Comment by navilan** [comment]
@khiltd - This is definitely the wrong repo.  Closing this. Responded to: https://github.com/hyde/hyde/issues/144

**Comment by ghost** [comment]
Why not close the whole repo and get rid of every public link to it? Google finds this one before it finds the other.
