### ISSUE TITLE
Document the proper way to exclude an .htaccess file

### ISSUE THREAD

**Issue by sjl** [hyde/hyde-old#9]
I have a `.htaccess` file at the root of my content directory to rewrite some old URLs.

I also have a feed.html file to serve http://stevelosh.com/feed/ as an atom feed.  In feed.xml I use `{% for node_page in page.node.walk_pages %}` to walk over all the posts to find the content to serve in the feed.

The problem is that the feed then includes the `.htaccess` file.

I tried adding a `{% hyde %}` tag in the `.htaccess` file in sjl/stevelosh@ef485be77a4e1f4b80bd60618ce4d9049dbd170a but it did not work.  It was just passed through and rendered in the `deploy/.htaccess` file, and Apache does not like that at all.

I ended up just checking the filename in the atom template in sjl/stevelosh@5c09be3c6b217152e1ce817d8d4eea62d69da986 for now, but that seems like a hacky solution.  Why doesn't the hyde tag in the `.htaccess` file get processed (and removed)?

**Comment by navilan** [comment]
1. `{% hyde %}`

The hyde tag gets excluded using Django's blocks. To use hyde tag in .htaccess, 
you can inherit from "skeleton/_root.html" in the default layout and enclose all other 
content other than the hyde tag in the `all` block. 
1. Checking for .htaccess:

When using `node.walk_pages` the loop should be bracketed with this condition to exclude 
files that are non-content (like listing pages, .htaccess and even atom.xml).
`{% if node_page.display_in_list %}`

---

I have been ok with the above two options. But if it is an issue we can think about 
a different solution.

**Comment by navilan** [comment]
I added documentation in templating guide for both the options above.

**Comment by alanhogan** [comment]
Huh, I’m still fairly confused. Where is `display_in_list` set? I am not manually using `node.walk_pages` and adding  {% hyde %} to .htaccess results in errors; adding

```
---
display_in_list: false
---
```

has no effect (my .htaccess is still getting wrapped in a template as it is copied to /deploy).

**Comment by navilan** [comment]
@alanhogan:

I think you are talking about the newer version of hyde at http://github.com/hyde/hyde.

The new version has the sorter plugin for filtering and sorting your listing pages. Here is an example for configuring the sorter plugin:
https://github.com/hyde/hyde/blob/master/hyde/layouts/basic/site.yaml#L44-51

Once you add the sorter, you can just do node.walk_pages_soted_by_<sorter_name> like this:
https://github.com/hyde/hyde/blob/master/hyde/layouts/basic/layout/listing.j2#L7-11

HTH
Lakshmi

**Comment by alanhogan** [comment]
_sigh_ I had no idea there were two separate projects & homepages for Hyde.
